Разметка index.html и catalog.html
htmlacademy-htmlcss/2209003-gllacy-35 pull request #2
Opened 2022-09-23 12:05 UTC by darvenommm

2022-09-24 01:54 UTC, Dima-Dim requested changes

2022-09-24 01:54 UTC, Dima-Dim commented on index.html
> +        <address class="address-phone">
Не думаю что тут стоит использовать тег `address`, можнь обойтись и без него.

2022-09-24 01:54 UTC, Dima-Dim commented on index.html
> +          <img class="introduction-image" src="#" alt="Клубничное мороженое">
Перечисление изображений очень похоже на список.

2022-09-24 01:54 UTC, Dima-Dim commented on index.html
> +        <div class="introduction-social-media">
На данном этапе не очевидно что списку нужен дополнительный контейнер.

2022-09-24 01:54 UTC, Dima-Dim commented on index.html
> +        <p class="flavors-main-text">Попробуйте самые популярные<br> вкусы нашего мороженого</p>
`<br>` больше относится к стилизации чем к разметке, поэтому пока его испоьзовать не нужно. Относится во всем тегам `br`.

2022-09-24 01:54 UTC, Dima-Dim commented on index.html
> +            <p class="about-us-desc">
Тег `p` тут может оказаться лишней обёрткой.

2022-09-24 01:54 UTC, Dima-Dim commented on index.html
> +      <div class="page-footer-social-media">
Сейчас тоже выглядит как лишняя обёртка.

2022-09-24 01:54 UTC, Dima-Dim commented on catalog.html
> +            <button class="flavors-pagination-button" type="button">
Почему `button`?

2022-09-24 15:43 UTC, darvenommm commented on index.html
> +        <address class="address-phone">
Почему нет? В тег address же засовывается контактная информация.

2022-09-24 17:22 UTC, darvenommm commented on catalog.html
> +            <button class="flavors-pagination-button" type="button">
Думал что реализация будет через js. Исправил.

2022-09-25 07:46 UTC, Dima-Dim commented on index.html
> +        <address class="address-phone">
Это ссылка на номер телефона и этого должно быть достаточно чтобы идентифицировать её как какую либо контактную информацию.

2022-09-25 07:47 UTC, Dima-Dim commented on catalog.html
> +            <button class="flavors-pagination-button" type="button">
Даже если так, по логике это ссылка на вполне конкретную страницу, а не интереактивный элемент который просто что-то переключает.

2022-09-26 15:06 UTC, merged